#!/usr/bin/env bash

if [ -z "$AWSENV_CF_DISTRIBUTION" ]; then 
  echo "AWSENV_CF_DISTRIBUTION is not set, cannot continue." >&2
  exit 1
fi

mydir="$(cd "$(dirname "$0")" && pwd)"
cd "$mydir/.."

npm run build

aws s3 sync ./dist s3://findvax-static-site\
 --profile findvax\
 --delete\
 --exclude ".DS_Store"\
 --output json

aws cloudfront create-invalidation\
 --profile findvax\
  --distribution-id=$AWSENV_CF_DISTRIBUTION\
  --paths /\*\
  --output json\
  | jq -r '.Invalidation'